#!/usr/bin/env python3
"""Assemble index.html from the step files in content/.

    python3 build.py           rebuild index.html
    python3 build.py --check   fail if index.html is out of date (used by CI)

No dependencies. Content lives in content/*.md, one step per file, ordered by
filename. See CONTRIBUTING.md.
"""
import sys, re, html, pathlib

ROOT = pathlib.Path(__file__).parent
MARKER = "/* STEPS: generated by build.py from content/*.md, do not edit here */"

# Every answer the form can produce. A typo in a step's `when:` fails the build
# rather than silently hiding that step from everyone forever.
VALUES = {
    "state":   ["NY", "NYC", "NJ", "CT"],
    "type":    ["mv", "hitrun", "door", "road", "solo", "ped"],
    "injury":  ["fatal", "severe", "head", "moderate", "minor"],
    "symptom": ["head", "neck", "bleed", "rash", "bone", "shoulder", "wrist",
                "chest", "abdo", "face", "numb", "fine"],
    "timing":  ["scene", "today", "later"],
    "police":  ["yes", "no", "unsure"],
}
FIELD = {"state": "a.state", "type": "a.type", "injury": "a.injury",
         "timing": "a.when", "police": "a.police"}
STYLES = ["urgent", "deadline"]


def fail(path, msg):
    sys.exit(f"{path}: {msg}")


def parse(path):
    text = path.read_text()
    if not text.startswith("---\n"):
        fail(path, "must start with a --- frontmatter block")
    fm, body = text[4:].split("\n---\n", 1)

    meta, when, in_when = {}, {}, False
    for line in fm.splitlines():
        if not line.strip():
            continue
        if line.startswith("  "):
            if not in_when:
                fail(path, f"indented line outside a when: block: {line.strip()}")
            k, _, v = line.strip().partition(":")
            when[k.strip()] = [x.strip() for x in v.strip().strip("[]").split(",") if x.strip()]
            continue
        k, _, v = line.partition(":")
        k, v = k.strip(), v.strip()
        in_when = (k == "when")
        if not in_when:
            meta[k] = v

    if not meta.get("title"):
        fail(path, "needs a title")
    if meta.get("style") and meta["style"] not in STYLES:
        fail(path, f"style must be one of {STYLES}, got {meta['style']!r}")
    for k in meta:
        if k not in ("title", "tag", "style", "when"):
            fail(path, f"unknown field {k!r}")

    for key, vals in when.items():
        base = key[:-4] if key.endswith("_not") else key
        if base not in VALUES:
            fail(path, f"unknown condition {key!r}; try one of "
                       f"{sorted(VALUES) + [k + '_not' for k in sorted(VALUES)]}")
        for v in vals:
            if v not in VALUES[base]:
                fail(path, f"{key}: {v!r} is not a valid answer; expected one of {VALUES[base]}")
    return meta, when, body.strip()


def compile_when(when):
    """Declarative conditions -> a JS predicate. Keys AND, values within a key OR."""
    parts = []
    for key, vals in when.items():
        neg = key.endswith("_not")
        base = key[:-4] if neg else key
        lst = "[" + ",".join(f'"{v}"' for v in vals) + "]"
        if base == "symptom":
            expr = f"{lst}.some(k=>has(a,k))"
        else:
            expr = f"{lst}.includes({FIELD[base]})"
        parts.append(("!" if neg else "") + expr)
    return "a=>" + " && ".join(parts) if parts else None


def md(text, path):
    """Markdown subset: paragraphs, - bullets, - [ ] checklists, **bold**,
    *italic*, [text](url). Everything else is literal."""
    def inline(t):
        t = html.escape(" ".join(t.split()), quote=False)
        t = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', t)
        t = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", t)
        t = re.sub(r"(?<![*\w])\*(?!\s)(.+?)(?<!\s)\*(?!\*)", r"<em>\1</em>", t)
        return t

    out = []
    for block in re.split(r"\n\s*\n", text.strip()):
        lines = [l for l in block.strip().splitlines() if l.strip()]
        if all(l.lstrip().startswith("- [ ] ") for l in lines):
            items = "".join(f"<li>{inline(l.lstrip()[6:])}</li>" for l in lines)
            out.append(f'<ul class="check">{items}</ul>')
        elif all(l.lstrip().startswith("- ") for l in lines):
            items = "".join(f"<li>{inline(l.lstrip()[2:])}</li>" for l in lines)
            out.append(f"<ul>{items}</ul>")
        else:
            if any(l.lstrip().startswith("- ") for l in lines):
                fail(path, "mixed list and paragraph in one block; separate them with a blank line")
            out.append(f"<p>{inline(' '.join(lines))}</p>")
    return "\n ".join(out)


def js(s):
    return s.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


def build():
    files = sorted((ROOT / "content").glob("*.md"))
    if not files:
        sys.exit("content/ is empty")
    entries = []
    for f in files:
        meta, when, body = parse(f)
        pred = compile_when(when)
        head = f"// {f.name}\n{{"
        if pred:
            head += f"when:{pred}, "
        if meta.get("style"):
            head += f'cls:"{meta["style"]}", '
        if meta.get("tag"):
            head += f'tag:"{meta["tag"]}", '
        title = js(meta["title"]).replace('"', '\\"')
        entries.append(f'{head}title:"{title}",\n html:`{js(md(body, f))}`}}')
    steps = "var STEPS = [\n\n" + ",\n\n".join(entries) + "\n\n];"

    tpl = (ROOT / "index.template.html").read_text()
    if MARKER not in tpl:
        sys.exit("index.template.html is missing the STEPS marker")
    return tpl.replace(MARKER, steps), len(files)


if __name__ == "__main__":
    page, n = build()
    target = ROOT / "index.html"
    if "--check" in sys.argv:
        if not target.exists() or target.read_text() != page:
            sys.exit("index.html is out of date. Run: python3 build.py")
        print(f"index.html is up to date ({n} steps)")
    else:
        target.write_text(page)
        print(f"wrote index.html from {n} steps")
